use database DBT;

use schema DBT_MAYANK;

SELECT CURRENT_DATE();

SELECT CURRENT_USER();

select current_role();

CREATE OR REPLACE SECRET DBT.DBT_MAYANK.GITHUB_PAT_TOKEN
  TYPE = PASSWORD
  USERNAME = 'icmayank-alt'
  PASSWORD = '';


ALTER GIT REPOSITORY tpch_sf_1 SET GIT_CREDENTIALS = DBT.DBT_MAYANK.GITHUB_PAT_TOKEN;

CREATE OR REPLACE GIT REPOSITORY DBT.DBT_MAYANK.tpch_sf_1 
	ORIGIN = 'https://github.com/icmayank-alt/tpch_sf_1.git' 
	API_INTEGRATION = 'GITHUB_API_INTEGRATION_FOR_TPCH1' 
	GIT_CREDENTIALS = 'DBT.DBT_MAYANK.GITHUB_PAT_TOKEN';



