-- Github needs to be connected to Workspace

USE ROLE USERADMIN;
-------------------
CREATE ROLE DATA_ENGINEER;
GRANT ROLE DATA_ENGINEER to ROLE SYSADMIN;

USE ROLE SYSADMIN;
------------------
CREATE DATABASE WS_DEMO_DB;
CREATE SCHEMA WS_DEMO_DB.STG;
CREATE WAREHOUSE DATA_ENGINEER_WH WAREHOUSE_SIZE = 'MEDIUM' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

USE ROLE SECURITYADMIN;
-----------------------
GRANT USAGE ON DATABASE WS_DEMO_DB TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA WS_DEMO_DB.STG TO ROLE DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE DATA_ENGINEER_WH TO ROLE DATA_ENGINEER;
GRANT CREATE VIEW, CREATE SECRET, CREATE STAGE, CREATE GIT REPOSITORY ON SCHEMA WS_DEMO_DB.STG TO ROLE DATA_ENGINEER;

USE ROLE ACCOUNTADMIN;
----------------------
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE_SAMPLE_DATA TO ROLE DATA_ENGINEER;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE DATA_ENGINEER;

USE ROLE DATA_ENGINEER;
-----------------------
USE WAREHOUSE DATA_ENGINEER_WH;
USE SCHEMA WS_DEMO_DB.STG;

-- CREATE SECRET:
-----------------
CREATE OR REPLACE SECRET GITHUB_TOKEN_SECRET
  TYPE = PASSWORD
  USERNAME = 'icmayank-alt'
  PASSWORD = '';
 
-- CREATE API Inegration:
-------------------------
CREATE OR REPLACE API INTEGRATION GITHUB_API_INTEGRATION
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com')
  ALLOWED_AUTHENTICATION_SECRETS = (GITHUB_TOKEN_SECRET)
  ENABLED = TRUE;
 
-- CREATE GIT Repo:
-------------------
CREATE OR REPLACE GIT REPOSITORY MY_GITHUB_REPO
  API_INTEGRATION = GITHUB_API_INTEGRATION
  GIT_CREDENTIALS = GITHUB_TOKEN_SECRET
  ORIGIN = 'https://github.com';
-- Error: Invalide Origin, Path cannot be empty